#!/bin/bash

# ============================================================
#  MEGA-Instances v2.0 — Multi-instance MEGAsync for Linux
#  https://github.com/NicoVarg99/MEGA-Instances
#
#  Runs multiple MEGAsync instances side-by-side, each with
#  its own HOME/XDG environment so accounts don't conflict.
#
#  Auto-detects your init system:
#    systemd  → per-instance systemd user services (KDE 6,
#               GNOME, etc.) — survives cold boots reliably.
#    non-systemd  → wrapper script + .desktop autostart
#               (Devuan, Alpine, Gentoo/OpenRC, Artix, Void…)
# ============================================================

# ── Configuration ───────────────────────────────────────────
VERSION="2.0"
REALHOME="$HOME"
MEGADIR="MEGA"
STATUS_DIR="$REALHOME/.config/megasync-instances"
STATUS_FILE="$STATUS_DIR/status"
SYSTEMD_USER_DIR="$REALHOME/.config/systemd/user"
ERR=0

# ── Detect init system ─────────────────────────────────────
# systemd is available when systemctl --user actually works
if command -v systemctl &>/dev/null && systemctl --user &>/dev/null 2>&1; then
    HAS_SYSTEMD=true
else
    HAS_SYSTEMD=false
fi

# ── Helpers ────────────────────────────────────────────────
zenity() { /usr/bin/zenity "$@" 2>/dev/null; }

checkDep() {
    if ! command -v "$1" &>/dev/null; then
        echo >&2 "Dependency '$1' seems to be missing"
        ERR=1
    fi
}

log() {
    echo "[MEGA-Instances] $*"
}

# ── Link KDE theme so dialogs look right ───────────────────
linkKdeGlobals() {
    local fake_home="$1"
    mkdir -p "$fake_home/.config"
    if [ ! -f "$fake_home/.config/kdeglobals" ]; then
        ln -sf "$REALHOME/.config/kdeglobals" "$fake_home/.config/kdeglobals" 2>/dev/null || true
    fi
}

# ── Launch one instance with isolated environment ──────────
launchInstance() {
    local fake_home="$1"
    HOME="$fake_home" \
    XDG_DATA_HOME="$fake_home/.local/share" \
    XDG_CONFIG_HOME="$fake_home/.config" \
    XDG_CACHE_HOME="$fake_home/.cache" \
    /usr/bin/megasync "$@"
}

# ── systemd methods ────────────────────────────────────────

generateService() {
    local name="$1"
    local home_dir="$REALHOME/$MEGADIR/$name"
    local unit_name="megasync-${name}.service"
    local file="$SYSTEMD_USER_DIR/$unit_name"

    mkdir -p "$SYSTEMD_USER_DIR"

    cat > "$file" << SERVICEEOF
[Unit]
Description=MEGAsync Instance - ${name}
Documentation=https://github.com/NicoVarg99/MEGA-Instances
PartOf=graphical-session.target
After=graphical-session.target network-online.target

[Service]
Type=simple
ExecStartPre=/bin/sleep 2
ExecStart=/usr/bin/megasync
Environment=HOME=${home_dir}
Environment=XDG_DATA_HOME=${home_dir}/.local/share
Environment=XDG_CONFIG_HOME=${home_dir}/.config
Environment=XDG_CACHE_HOME=${home_dir}/.cache
Restart=on-failure
RestartSec=10
TimeoutStopSec=10

[Install]
WantedBy=graphical-session.target
SERVICEEOF

    chmod 644 "$file"
    log "Generated systemd service: $unit_name"
}

cleanOldAutostart() {
    local old_desktop="$REALHOME/.config/autostart/mega_instances.desktop"
    if [ -f "$old_desktop" ]; then
        mv "$old_desktop" "${old_desktop}.bak" 2>/dev/null
        log "Backed up old autostart .desktop file"
    fi
    # Disable old generated service if it exists
    local gen_service="app-megasync\\x2dinstances@autostart.service"
    if systemctl --user is-enabled "$gen_service" &>/dev/null; then
        systemctl --user disable "$gen_service" 2>/dev/null || true
        log "Disabled old generated systemd service"
    fi
}

startAllSystemd() {
    log "Starting all instances via systemd..."
    for svc in "$SYSTEMD_USER_DIR"/megasync-*.service; do
        [ -f "$svc" ] || continue
        local name
        name=$(basename "$svc" .service | sed 's/^megasync-//')
        log "  Starting megasync-${name}.service..."
        systemctl --user start "megasync-${name}.service" 2>/dev/null || {
            log "  WARNING: Failed to start megasync-${name}.service"
        }
    done
    log "Done. Instances will also start automatically at next login."
}

# ── Non-systemd methods (wrapper + .desktop) ───────────────

generateWrapper() {
    local wrapper_path="$REALHOME/.local/bin/megasync-instances-launcher.sh"
    mkdir -p "$(dirname "$wrapper_path")"

    cat > "$wrapper_path" << 'WRAPPEREOF'
#!/bin/bash
# Auto-generated by MEGA-Instances — launches all instances
REALHOME="$HOME"
MEGADIR="MEGA"
for d in "$REALHOME/$MEGADIR"/*/; do
    [ -d "$d" ] || continue
    HOME="$d" \
    XDG_DATA_HOME="$d/.local/share" \
    XDG_CONFIG_HOME="$d/.config" \
    XDG_CACHE_HOME="$d/.cache" \
    /usr/bin/megasync 2>/dev/null &
    sleep 3
done
WRAPPEREOF

    chmod 755 "$wrapper_path"
    log "Generated wrapper script: $wrapper_path"
}

generateDesktopEntry() {
    local desktop_path="$REALHOME/.config/autostart/mega_instances.desktop"
    mkdir -p "$(dirname "$desktop_path")"

    cat > "$desktop_path" << DESKTOPEOF
[Desktop Entry]
Type=Application
Exec=$REALHOME/.local/bin/megasync-instances-launcher.sh
Name=megasync_instances
Comment=Open all your MEGA instances
DESKTOPEOF

    chmod 755 "$desktop_path"
    log "Generated autostart .desktop entry: $desktop_path"
}

startAllWrapper() {
    local wrapper_path="$REALHOME/.local/bin/megasync-instances-launcher.sh"
    if [ -x "$wrapper_path" ]; then
        log "Starting all instances via wrapper script..."
        bash "$wrapper_path"
    else
        log "ERROR: Wrapper script not found at $wrapper_path"
        exit 1
    fi
}

# ── First-time configuration ──────────────────────────────
finstall() {
    checkDep zenity
    checkDep megasync

    if [ $ERR -ne 0 ]; then
        echo >&2 "Error: Install all required dependencies before running MEGA-Instances"
        exit 1
    fi

    if $HAS_SYSTEMD; then
        log "Detected systemd — will use per-instance systemd services"
    else
        log "No systemd detected — will use wrapper script + .desktop autostart"
    fi

    frun
}

frun() {
    if [ -f "$STATUS_FILE" ] && [ "$(cat "$STATUS_FILE")" = "1" ]; then
        # ── Already configured — launch ─────────────────────
        log "MEGA-Instances is already configured."

        if $HAS_SYSTEMD; then
            startAllSystemd
        else
            startAllWrapper
        fi

    else
        # ── First-time setup ───────────────────────────────
        log "MEGA-Instances is not configured. Starting setup..."

        if ! zenity --question --no-wrap \
            --text="This is the first time you are running MEGA-Instances.\n\nIn order to continue we must delete your existing MEGA instance.\nPress Yes to continue, No to abort."; then
            exit
        fi

        # Remove old single-instance data
        killall megasync 2>/dev/null
        rm -rf "$REALHOME/$MEGADIR"
        rm -f "$REALHOME/.config/autostart/megasync.desktop"

        # Ask how many instances
        INSTNUM=$(zenity --entry --text="How many MEGA instances do you need?")
        [ -z "$INSTNUM" ] && exit
        mkdir -p "$REALHOME/$MEGADIR"

        # Collect instance names
        ARRAY=()
        for (( i=1; i<=INSTNUM; i++ )); do
            NAME=$(zenity --entry --text="Insert the name for instance $i/$INSTNUM")
            [ -z "$NAME" ] && exit
            ARRAY+=("$NAME")
            mkdir -p "$REALHOME/$MEGADIR/$NAME"
        done

        # Launch each instance for initial login (one at a time)
        for (( i=0; i<INSTNUM; i++ )); do
            local name="${ARRAY[$i]}"
            local fake_home="$REALHOME/$MEGADIR/$name"

            # Prepare directories
            mkdir -p "$fake_home/.config"
            mkdir -p "$fake_home/.local/share/data/Mega Limited/MEGAsync"
            mkdir -p "$fake_home/.cache"
            linkKdeGlobals "$fake_home"

            zenity --warning \
                --text="Instance ${name} ($((i+1))/$INSTNUM).\n\nLog in and then CLOSE the MEGAsync window.\nDo NOT just close to tray — quit the application."

            launchInstance "$fake_home"
        done

        # Generate autostart mechanism
        if $HAS_SYSTEMD; then
            # Generate and enable systemd services
            for name in "${ARRAY[@]}"; do
                generateService "$name"
            done
            systemctl --user daemon-reload
            for name in "${ARRAY[@]}"; do
                systemctl --user enable "megasync-${name}.service"
                log "Enabled megasync-${name}.service for autostart"
            done
            cleanOldAutostart
        else
            # Generate wrapper script + .desktop entry
            generateWrapper
            generateDesktopEntry
        fi

        # Mark as configured
        echo 1 > "$STATUS_FILE"

        zenity --warning \
            --text="Configuration complete!\n\nAll instances will now start.\nThey will also start automatically at every login."

        # Launch all instances
        frun
    fi
}

# ── Entry point ───────────────────────────────────────────
mkdir -p "$STATUS_DIR"

if ! $HAS_SYSTEMD; then
    mkdir -p "$SYSTEMD_USER_DIR"  # harmless even without systemd
fi

if [ ! -f "$STATUS_FILE" ]; then
    echo 0 > "$STATUS_FILE"
fi

finstall
